import glob
import os
import pathlib
from dds.timecache import its_time_to
from mat.data_converter import default_parameters, DataConverter
from mat.data_file_factory import load_data_file
from mat.lix import convert_lix_file
from mat.utils import linux_ls_by_ext
from utils.logs import lg_cnv as lg
from utils.ddh_shared import (
    send_ddh_udp_gui as _u,
    get_ddh_folder_path_dl_files,
    STATE_DDS_NOTIFY_CONVERSION_ERR,
    STATE_DDS_NOTIFY_CONVERSION_OK,
)
import pandas as pd


"""
code in this file only takes care of LID data files
"""


PERIOD_CNV_SECS = 3600 * 12
BAROMETRIC_PRESSURE_SEA_LEVEL_IN_DECIBAR = 10.1
DDH_BPSL = BAROMETRIC_PRESSURE_SEA_LEVEL_IN_DECIBAR


_g_files_we_cannot_convert = []
_g_files_already_converted = []
_g_last_nf = 0


def _lid_file_has_sensor_data_type(path, suffix):
    _map = {"_DissolvedOxygen": "DOS", "_Temperature": "TMP", "_Pressure": "PRS"}
    header = load_data_file(path).header()
    return header.tag(_map[suffix])


def _cnv_lid(fol, suf) -> (bool, list):

    # check asked folder (ex: dl_files/e5-fc-4e-94-ed-dd) exists
    if not pathlib.Path(fol).is_dir():
        lg.a("error: folder {} not found".format(fol))
        return False, []

    # check asked suffix (ex: _DissolvedOxygen) exists
    valid_suffixes = ("_DissolvedOxygen", "_Temperature", "_Pressure")
    if suf not in valid_suffixes:
        lg.a("error: unknown suffix {}".format(suf))
        return False, []

    # --------------------------
    # we only convert LID files
    # --------------------------
    parameters = default_parameters()
    err_files = []
    all_ok = True
    global _g_files_we_cannot_convert
    lid_files = linux_ls_by_ext(fol, "lid")

    for f in lid_files:
        # do not convert test_files
        if os.path.basename(f).startswith('test'):
            continue
        # do not convert when already have CSV files for this LID file
        _ = "{}{}.csv".format(f.split(".")[0], suf)
        if pathlib.Path(_).is_file():
            global _g_files_already_converted
            s = "debug: skip conversion, file {} already exists"
            if _ not in _g_files_already_converted:
                lg.a(s.format(_))
                _g_files_already_converted.append(_)
            continue

        # do not convert when LID file already known as defective
        if f in _g_files_we_cannot_convert:
            continue

        # -----------------------------
        # try to convert this LID file
        # -----------------------------
        try:
            # skip files not containing this sensor data
            if not _lid_file_has_sensor_data_type(f, suf):
                # s = 'debug: skip conversion, file {} has no {} data'
                # lg.a(s.format(f, suf))
                continue

            DataConverter(f, parameters).convert()
            lg.a("converted file {} for suffix {}".format(f, suf))

            # --------------------------------
            # RN4020: hack for pressure adjust
            # --------------------------------
            if ("_Pressure" in suf) and ("moana" not in f.lower()):
                lg.a("debug: adjusting LI file {}".format(f))
                fp_csv = f[:-4] + "_Pressure.csv"
                df = pd.read_csv(fp_csv)
                c = "Pressure (dbar)"
                df[c] = df["Pressure (dbar)"] - DDH_BPSL
                df[c] = df[c].apply(lambda x: x if x > 0 else 0)
                df.to_csv(fp_csv, index=False)

        except (ValueError, Exception) as ex:

            all_ok = False
            err_files.append(f)
            e = "error: converting file {}, metric {} --> {}"
            lg.a(e.format(f, suf, str(ex)))

            # add to black list of files
            if f not in _g_files_we_cannot_convert:
                e = "warning: ignoring file {} for metric {} from now on"
                lg.a(e.format(f, suf))
                _g_files_we_cannot_convert.append(f)

    return all_ok, err_files


# external alias for this function
def convert_lid_to_csv(fol, suf) -> (bool, list):
    return _cnv_lid(fol, suf)


def _cnv_lid_metric(m):
    fol = str(get_ddh_folder_path_dl_files())
    rv, _ = _cnv_lid(fol, m)
    return rv


def _cnv_all_lix_files():
    fol = str(get_ddh_folder_path_dl_files())
    if not fol or not os.path.isdir(fol):
        # None means error
        return

    # collect all LIX files generated by any logger type
    global _g_files_we_cannot_convert
    global _g_files_already_converted
    _g_files_already_converted = glob.glob('/**/*.csv', recursive=True)

    # global result of all file conversions
    rv_all = 0

    for f in glob.glob(fol + '/**/*.lix', recursive=True):
        # cases no conversion needed
        fc = f[:-4] + '.csv'
        if fc in _g_files_already_converted:
            lg.a(f"debug: skip conversion, file {fc} already exists")
            continue
        if f in _g_files_we_cannot_convert:
            continue
        #
        # # try to convert it
        # plf = ParserLixFile(f)
        # rv = plf.convert_lix_file()
        #
        # # populate lists
        # if rv and f not in _g_files_we_cannot_convert:
        #     lg.a(f"warning: ignoring file {f} from now on")
        #     _g_files_we_cannot_convert.append(f)
        # rv_all += rv

    # check not a single file had errors
    return rv_all == 0


def _cnv_serve():

    # detect we have to force a conversion sequence
    fol = str(get_ddh_folder_path_dl_files())
    global _g_last_nf
    ls = glob.glob(f'{fol}/**/*.lid', recursive=True)
    forced = len(ls) != _g_last_nf
    if forced:
        lg.a(f'OK: #LID files {_g_last_nf} -> {len(ls)}, conversion forced')
    _g_last_nf = len(ls)

    # this function does not run always, only from time to time
    if not its_time_to("do_some_conversions", PERIOD_CNV_SECS) and not forced:
        return

    # this function does not run always, only from time to time
    if not its_time_to("do_some_conversions", PERIOD_CNV_SECS):
        return

    # general banner
    s = 'debug: conversion sequence started'
    lg.a('-' * len(s))
    lg.a(s)

    # error variable
    e = ""

    # this one includes WATER
    s = "some {} .lid files did not convert"
    m = "_DissolvedOxygen"
    rv = _cnv_lid_metric(m)
    if not rv:
        e += "O_"
        lg.a(s.format(m))

    m = "_Temperature"
    rv = _cnv_lid_metric(m)
    if not rv:
        e += "T_"
        lg.a(s.format(m))

    m = "_Pressure"
    rv = _cnv_lid_metric(m)
    if not rv:
        e += "P_"
        lg.a(s.format(m))

    # rv = _cnv_all_lix_files()
    # if not rv:
    #     e += 'LIX_'
    #     lg.a(s.format('_LIX'))

    s = 'conversion sequence finished'
    lg.a(s)
    lg.a('-' * len(s))

    # GUI update
    if e:
        _u("{}/{}".format(STATE_DDS_NOTIFY_CONVERSION_ERR, e))
    else:
        _u("{}/OK".format(STATE_DDS_NOTIFY_CONVERSION_OK))


def cnv_serve():
    try:
        _cnv_serve()
    except (Exception, ) as ex:
        e = 'error: conversion exception ex ->'
        if its_time_to(e, 3600 * 6):
            lg.a(f'{e} {ex}')


if __name__ == '__main__':
    fol = str(get_ddh_folder_path_dl_files())
    f = fol + '/d0-2e-ab-d9-29-48/9999999_BIL_20240209_165512.lix'
    convert_lix_file(f)
