PERIOD_GPS_CACHE_VALID_SECS = 30
PERIOD_GPS_TELL_NUM_SATS_SECS = 100
PERIOD_GPS_TELL_VESSEL_SECS = 30
PERIOD_GPS_AT_BOOT_SECS = 600
PERIOD_GPS_TELL_GPS_HW_ERROR_SECS = 3600 * 3
PERIOD_GPS_TELL_PUCK_NO_PC = 3600 * 6
PERIOD_GPS_POWER_CYCLE = 300
PERIOD_GPS_NOTI_NUM_GPS_SAT = 1800
